## Box Plots
- Making Box Plots using available data

In [12]:
#Importing Libraries
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

#importing data set

df=pd.read_csv(r'C:\Users\Mujahid\Desktop\python_with_aammar\Chilla_data2_for_plots.csv')
df

,Gender,Location,Age,Qualification_completed,field_of_study,Purpose_for_chilla,What are you?,Blood group,Which mobile sim do you use,Prepaid or Postpaid,...,Your favorite programming language?,Marital Status?,Are you Vaccinated?,Where do you live?,Research/Working experience (Float/Int) years,Age (years)-Float/Int,Your Weight in kg? (float),Height in cm? Freelancer- (Float),"How many hours you code a day? (int) e.g: 5,4,3",Light kitni der band hti hy? int
0,Male,Pakistan,36-40,Masters,Natural Sciences,to boost my skill set,Unemplyed,B+,U-fone,Prepaid,...,Python,Yes,Yes,Urbun,5.0,38.00,77.0,179.000,3.0,2
1,Male,Pakistan,26-30,Bachelors,CS/IT,to boost my skill set,Student,B+,U-fone,Prepaid,...,Python,No,Yes,Urbun,1.0,25.00,53.6,178.000,2.0,6
2,Male,Pakistan,31-35,Masters,Enginnering,Switch my field of study,Employed,B+,Zong,Prepaid,...,Python,Yes,Yes,Urbun,5.5,31.34,93.0,173.000,2.0,0
3,Female,Pakistan,31-35,Masters,CS/IT,to boost my skill set,Employed,O+,U-fone,Postpaid,...,Python,Yes,Yes,Urbun,5.0,33.00,60.0,157.000,3.0,24
4,Female,Pakistan,26-30,Masters,Enginnering,to boost my skill set,Student,A-,Mobilink,Prepaid,...,Javascript,No,Yes,Rural,3.5,27.00,59.9,164.544,6.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,Male,Pakistan,26-30,Masters,Enginnering,to boost my skill set,Employed,O+,Telenor,Prepaid,...,R,Yes,Yes,Rural,7.0,28.00,70.5,178.500,4.0,3
371,Male,Pakistan,31-35,Bachelors,Enginnering,to boost my skill set,Employed,A+,Zong,Postpaid,...,Python,Yes,Yes,Urbun,5.0,33.00,83.4,172.700,1.0,1
372,Male,Pakistan,21-25,Bachelors,CS/IT,to boost my skill set,Employed,O+,Mobilink,Prepaid,...,Python,No,Yes,Urbun,0.0,22.80,60.0,1.680,0.0,0
373,Male,Pakistan,26-30,Masters,Enginnering,to boost my skill set,Employed,B-,Mobilink,Prepaid,...,Python,No,No,Urbun,2.0,29.00,86.0,180.000,2.0,1
374,Female,Pakistan,31-35,Masters,Mathematics,Switch my field of study,Unemplyed,B+,Telenor,Prepaid,...,Python,Yes,Yes,Urbun,3.0,31.00,54.5,161.544,3.0,0

In [43]:
#Importing Libraries
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

#importing data set
palette=sns.color_palette('rocket_r')
df=pd.read_csv(r'C:\Users\Mujahid\Desktop\python_with_aammar\Chilla_data2_for_plots.csv')
p=sns.relplot(x="Age (years)-Float/Int", y="Your Weight in kg? (float)", hue="How many hours you code a day? (int) e.g: 5,4,3", 
              col="Gender", 
              kind="line", palette=palette, data=df )
plt.show()

ValueError: The palette list has the wrong number of colors.

In [61]:
#Importing Libraries
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

palette = sns.color_palette("rocket_r")

# Plot the lines on two facets
sns.relplot(
    data=df,
    x="Age (years)-Float/Int", y="Your Weight in kg? (float)",
     size="Marital Status?", col="Gender", 
    kind="line", size_order=["Yes", "No"], palette=palette,
    height=5, aspect=.75, facet_kws=dict(sharex=False),
)

ValueError: The palette list has the wrong number of colors.